services:
  tba_db: 
    image: mysql:8.0
    container_name: tba_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: cog                
      MYSQL_USER: newroot               
      MYSQL_PASSWORD: mypassword        
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  tba_web:
    build: .
    command: /var/www/html/project/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - tba_db
volumes:
  mysql_data: