# Generated by Django 5.0.3 on 2024-11-06 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('users', '0004_alter_cars_user_alter_history_user_alter_rating_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField(default=0)),
                ('free_places', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('baggage', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='car', to='users.cars')),
                ('from_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_city', to='cities.cities')),
                ('to_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_city', to='cities.cities')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('places', models.IntegerField(default=1)),
                ('total_price', models.IntegerField(default=0)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='ride.ride')),
            ],
        ),
    ]
